services:
  vault:
    image: psazevedo/vault:latest
    command: vault server -config=/hc-vault/vault.hcl
    restart: unless-stopped
    volumes:
      - /data/vault/file:/vault/file
      - /data/vault/logs:/vault/logs
      - /data/vault/config:/vault/config
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_API_ADDR: http://127.0.0.1:8200
      VAULT_SKIP_VERIFY: "true"
    cap_add:
      - IPC_LOCK