#!/bin/bash

json="$1"
if [ -z "${json}" ]; then
  echo "Please provide a JSON file path as argument."
  exit 1
fi

json=$(cat $1)

vaults=$(echo "$json" | jq -r '.')

for vault in $(echo "$vaults" | jq -c '.[]'); do
  vault_name=$(echo "$vault" | jq -r '.vault')
  prefix=$(echo "$vault" | jq -r '.prefix')
  env=$(echo "$vault" | jq -r '.env')
  secrets=$(echo "$vault" | jq -r '.secrets')

  for secret in $(echo "$secrets" | jq -c '.[]'); do
    name=$(echo "$secret" | jq -r '.name')
    value=$(echo "$secret" | jq -r '.value')
    type=$(echo "$secret" | jq -r '.type')
    secret_name="$prefix-$env-$name"
    echo "$secret_name, $value, $type"
    az keyvault secret set --vault-name "$vault_name" --name "$secret_name" --value "$value" --description "$type"
  done
done
